/**
 * Cabeçalhos exatos da planilha "ORGÂNICO DEFINITIVO GRUPO_ SÓ AÇO.xlsx".
 * Ordem e texto devem ser mantidos para importação/exportação.
 */
export const ORGANICO_HEADERS: string[] = [
  "MATRICULA",
  "NOME",
  "CPF",
  "RG",
  "CNH - CATEGORIA",
  "NUMERO - CNH",
  "CARGA HORÁRIA MENSAL",
  "TURNO",
  "ESCALA DE TRABALHO",
  "SEXO",
  "ADMISSÃO",
  "TEMPO DE EMPRESA",
  "CARGO",
  "AREÁ",
  "SETOR",
  "GESTOR IMEDIATO",
  "GESTOR MEDIATO",
  "DIRETORIA",
  "PIS",
  "Nascimento",
  "Idade",
  "Grau Instrução",
  "Curso Graduação",
  "Período",
  "Ano previsto para Formatura",
  "Especialidade/MBA?",
  "CBO",
  "Vínculo",
  "Número de filhos",
  "Número de dependentes",
  "Telefone",
  "Telefone Emergencial",
  "Tamanho Calçado",
  "Tamanho Camisa",
  "Tamanho Calça",
  "EPI´s LOCUS",
  "EPI´s ESCOPO",
  "PCD",
  "Vale Transporte",
  "QTD( 2 ou 4 )",
  "Valor (Vale)",
  "$$ (valor diário)",
  "$$ ( consid. 21 Dias Uts )",
  "Desconto VT",
  "Auxílio Combustível",
  "Quant de litros ( semanal )",
  "Valor do litro",
  "$ Semanal",
  "$$ ( consid. 4 Semanas Uts )",
  "Auxílio Quentinha",
  "$ Dia",
  "$$ ( consid. 21 Dias Uts ).",
  "TOTAL MÊS ( VT + VA + GASO )",
  "CTPS",
  "FAIXA SALÁRIAL",
  "Insalubridade ( REF - SALÁRIO MINIMO )",
  "INCRE %",
  "INCRE $$",
  "Periculosidade ( REF - SALÁRIO FUNCIONÁRIO )",
  "INCRE %2",
  "INCRE $$2",
  "Adicional noturno",
  "INCRE %4",
  "INCRE $$5",
  "Salário Familia",
  "QTD Filhos",
  "INCRE $$6",
  "Cargo Confiança",
  "Percentual %",
  "INCRE $$7",
  "TOTAL INCRE $$8",
  "SOMENTE SALÁRIO",
  "Adendo",
  "SALÁRIO + ADENDO",
  "SALÁRIO + ADENDO + ADICIONAIS",
  "CUSTO TOTAL - GERAL - CR MÊS",
  "AGENCIA",
  "CONTA",
  "BANCO",
  "CHAVE PIX",
  "CASO NÃO TENHA PIX",
  "ONBOARDING",
  "MODAL GESTÃO DE HORAS",
  "SITUAÇÃO TRABALHISTA",
  "STATUS FUNCIONÁRIO",
  "ESTABILIDADE",
  "DETALHAMENTO ARQUIVO",
];

/** Quantidade de colunas do orgânico (evita número mágico 86 espalhado no código). */
export const ORGANICO_NUM_COLUNAS = ORGANICO_HEADERS.length;
