import { PERMISSOES, type CodigoPermissao } from './permissoes';

export const PERMISSOES_ACESSO_COMERCIAL_PAINEL: CodigoPermissao[] = [
  PERMISSOES.COMERCIAL_VER,
  PERMISSOES.COMERCIAL_PAINEL_VER,
];

export const PERMISSOES_ACESSO_COMERCIAL_HISTORICO_VENDAS: CodigoPermissao[] = [
  PERMISSOES.COMERCIAL_VER,
  PERMISSOES.COMERCIAL_HISTORICO_VENDAS_VER,
];
