import { PERMISSOES, type CodigoPermissao } from '../config/permissoes.js';

export const PERMISSOES_ACESSO_FINANCEIRO_RESUMO: CodigoPermissao[] = [
  PERMISSOES.FINANCEIRO_VER,
  PERMISSOES.FINANCEIRO_RESUMO_VER,
];

export const PERMISSOES_ACESSO_FINANCEIRO_DRE: CodigoPermissao[] = [
  PERMISSOES.FINANCEIRO_VER,
  PERMISSOES.FINANCEIRO_DRE_VER,
];

export const PERMISSOES_ACESSO_FINANCEIRO_DFC: CodigoPermissao[] = [
  PERMISSOES.FINANCEIRO_VER,
  PERMISSOES.FINANCEIRO_DFC_VER,
];

export const PERMISSOES_ACESSO_FINANCEIRO_PAINEL_COMERCIAL: CodigoPermissao[] = [
  PERMISSOES.FINANCEIRO_VER,
  PERMISSOES.FINANCEIRO_PAINEL_COMERCIAL_VER,
];

export const PERMISSOES_ACESSO_FINANCEIRO_RENEGOCIACAO: CodigoPermissao[] = [
  PERMISSOES.FINANCEIRO_VER,
  PERMISSOES.FINANCEIRO_RENEGOCIACAO_CONTRATOS_VER,
];

/** Guia "Situação geral da empresa" do CRM. */
export const PERMISSOES_ACESSO_FINANCEIRO_CRM_EMPRESA: CodigoPermissao[] = [
  PERMISSOES.FINANCEIRO_VER,
  PERMISSOES.FINANCEIRO_CRM_VER,
  PERMISSOES.FINANCEIRO_CRM_EMPRESA_VER,
];

/** Guia "Análise de crédito por cliente" do CRM. */
export const PERMISSOES_ACESSO_FINANCEIRO_CRM_CLIENTE: CodigoPermissao[] = [
  PERMISSOES.FINANCEIRO_VER,
  PERMISSOES.FINANCEIRO_CRM_VER,
  PERMISSOES.FINANCEIRO_CRM_CLIENTE_VER,
];

/** Guia "Pendências de crédito com PD em carteira" do CRM. */
export const PERMISSOES_ACESSO_FINANCEIRO_CRM_PENDENCIAS: CodigoPermissao[] = [
  PERMISSOES.FINANCEIRO_VER,
  PERMISSOES.FINANCEIRO_CRM_VER,
  PERMISSOES.FINANCEIRO_CRM_PENDENCIAS_VER,
];

/** Editar To/Cc do e-mail de ação na aba Pendências. */
export const PERMISSOES_EDITAR_CRM_PENDENCIAS_DESTINATARIOS: CodigoPermissao[] = [
  PERMISSOES.FINANCEIRO_VER,
  PERMISSOES.FINANCEIRO_CRM_VER,
  PERMISSOES.FINANCEIRO_CRM_PENDENCIAS_DESTINATARIOS_EDITAR,
];

/** Acesso à tela do CRM (qualquer uma das guias). */
export const PERMISSOES_ACESSO_FINANCEIRO_CRM: CodigoPermissao[] = [
  PERMISSOES.FINANCEIRO_VER,
  PERMISSOES.FINANCEIRO_CRM_VER,
  PERMISSOES.FINANCEIRO_CRM_EMPRESA_VER,
  PERMISSOES.FINANCEIRO_CRM_CLIENTE_VER,
  PERMISSOES.FINANCEIRO_CRM_PENDENCIAS_VER,
];

export const PERMISSOES_ACESSO_FINANCEIRO_CARTEIRA: CodigoPermissao[] = [
  PERMISSOES.FINANCEIRO_VER,
  PERMISSOES.FINANCEIRO_CARTEIRA_FINANCEIRA_VER,
];