import { PERMISSOES, type CodigoPermissao } from '../config/permissoes.js';

export const PERMISSOES_ACESSO_SEQUENCIAMENTO_CARRADAS: CodigoPermissao[] = [
  PERMISSOES.PCP_SEQUENCIAMENTO_CARRADAS_VER,
  PERMISSOES.PCP_SEQUENCIAMENTO_CARRADAS_CRIAR,
  PERMISSOES.PCP_TOTAL,
  PERMISSOES.PCP_VER_TELA,
  PERMISSOES.PEDIDOS_VER,
];

export const PERMISSOES_EDITAR_SEQUENCIAMENTO_CARRADAS: CodigoPermissao[] = [
  PERMISSOES.PCP_SEQUENCIAMENTO_CARRADAS_CRIAR,
  PERMISSOES.PCP_TOTAL,
  PERMISSOES.PCP_VER_TELA,
  PERMISSOES.PEDIDOS_EDITAR,
];
